eswin: add missing include dm/pinctrl.h in board file
Avoid a build failure

    board/eswin/hifive_premier_p550/hifive_premier_p550.c:234:12: error:
    implicit declaration of function ‘pinctrl_select_state’
    [-Wimplicit-function-declaration]
      234 |         if(pinctrl_select_state(pinctrl, "default")) {
          |            ^~~~~~~~~~~~~~~~~~~~

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>